---
# This playbook deploys a simple kubeadm install.
- name: Bootstrap Tasks
  hosts: 
    - "{{ master_node }}"
    - "{{ worker_node }}"
  remote_user: "{{ ansible_remote_user }}"
  gather_facts: False
  roles:
    - common

- name: Install Kubernetes master
  hosts: "{{ master_node }}"
  remote_user: "{{ ansible_remote_user }}"
  become: yes
  become_method: sudo
  roles:
    - docker
    - kubeadm
    - master

- name: Install nodes
  remote_user: "{{ ansible_remote_user }}"
  hosts: "{{ worker_node }}"
  become: yes
  become_method: sudo
  roles:
    - docker
    - kubeadm
    - worker

- import_playbook: deploy_contiv_network_config.yml
